[package]
name = "wrusdummy"
version = "0.0.10"
edition = "2021"

[dependencies]
wruster = { path = "../wruster" }
wruster_handlers = { path = "../wruster_handlers" }
log = "0.4.14"
env_logger = "0.8.4"
mime = "0.3.16"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
